// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEsyTjsZoti-XTwRsWoe0OfMmvetROiHs',
    appId: '1:177916055945:web:648bdce314504106241158',
    messagingSenderId: '177916055945',
    projectId: 'login-sample-bf95d',
    authDomain: 'login-sample-bf95d.firebaseapp.com',
    storageBucket: 'login-sample-bf95d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf5vlPIrSed0k7LpA4P6BDFAQHLpreapo',
    appId: '1:177916055945:android:1d1df082f7ec107c241158',
    messagingSenderId: '177916055945',
    projectId: 'login-sample-bf95d',
    storageBucket: 'login-sample-bf95d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPuHbF-d84OWX9FpCp3q3ZbqngOWf9H5U',
    appId: '1:177916055945:ios:25aeaf67e439b1ea241158',
    messagingSenderId: '177916055945',
    projectId: 'login-sample-bf95d',
    storageBucket: 'login-sample-bf95d.firebasestorage.app',
    iosBundleId: 'com.example.plaTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPuHbF-d84OWX9FpCp3q3ZbqngOWf9H5U',
    appId: '1:177916055945:ios:25aeaf67e439b1ea241158',
    messagingSenderId: '177916055945',
    projectId: 'login-sample-bf95d',
    storageBucket: 'login-sample-bf95d.firebasestorage.app',
    iosBundleId: 'com.example.plaTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEsyTjsZoti-XTwRsWoe0OfMmvetROiHs',
    appId: '1:177916055945:web:e31392ec4990d89b241158',
    messagingSenderId: '177916055945',
    projectId: 'login-sample-bf95d',
    authDomain: 'login-sample-bf95d.firebaseapp.com',
    storageBucket: 'login-sample-bf95d.firebasestorage.app',
  );
}
